$: dropin.recipes/Automations/Deployment

services:
  kiwi-bundle-react:
    context: .

    runtime: { name: node }

    dependencies:
      kiwi-bundle: blueforest:kiwi/core:v1:kiwi-bundle
      dropin-client: blueforest:dropin/client:v1:dropin-client-js

    tasks:
      start:
        name: Watch and build
        command: start

      build:
        name: Build production files
        command: build
